platform :ios, '7.0'

target "newsmyEye" do

pod "AFNetworking","~>3.1.0"
pod "SVProgressHUD", "~> 2.0-beta8"
pod "CocoaFFmpeg", "~> 2.2.0"
pod "Masonry", "~> 1.0"
pod "ZBarSDK", "~> 1.3.1"
pod "KxMenu", "~> 1"
pod 'MJRefresh'
pod 'JPush', '~> 2.1.5'
pod 'LMAlertView', '~> 1.1.0'
pod 'FMDB', '~> 2.6.2'
pod 'UMengAnalytics-NO-IDFA'
pod 'CocoaLumberjack'

pod 'SDWebImage', '~> 3.8.1'

pod 'FLEX', '~> 2.0', :configurations => ['Debug']
pod 'UITableView+FDTemplateLayoutCell_Bell', '~> 1.5.0'

end
